# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ListSelector = QtWidgets.QListWidget(self.centralwidget)
        self.ListSelector.setGeometry(QtCore.QRect(540, 80, 256, 501))
        self.ListSelector.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.ListSelector.setObjectName("ListSelector")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(810, 620, 89, 25))
        self.AddButton.setObjectName("AddButton")
        self.CsvVisualizer = QtWidgets.QTableWidget(self.centralwidget)
        self.CsvVisualizer.setGeometry(QtCore.QRect(30, 80, 481, 501))
        self.CsvVisualizer.setObjectName("CsvVisualizer")
        self.CsvVisualizer.setColumnCount(0)
        self.CsvVisualizer.setRowCount(0)
        self.ConfirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmButton.setGeometry(QtCore.QRect(810, 270, 131, 25))
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.AddOption = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.AddOption.setGeometry(QtCore.QRect(540, 600, 261, 70))
        self.AddOption.setObjectName("AddOption")
        self.FilterBox = QtWidgets.QCheckBox(self.centralwidget)
        self.FilterBox.setGeometry(QtCore.QRect(140, 600, 191, 41))
        self.FilterBox.setObjectName("FilterBox")
        self.LoadOptions = QtWidgets.QPushButton(self.centralwidget)
        self.LoadOptions.setGeometry(QtCore.QRect(510, 40, 151, 25))
        self.LoadOptions.setObjectName("LoadOptions")
        self.RemoveOption = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveOption.setGeometry(QtCore.QRect(690, 40, 121, 25))
        self.RemoveOption.setObjectName("RemoveOption")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 22))
        self.menubar.setObjectName("menubar")
        self.menuOpenFile = QtWidgets.QMenu(self.menubar)
        self.menuOpenFile.setObjectName("menuOpenFile")
        self.menuCategories = QtWidgets.QMenu(self.menubar)
        self.menuCategories.setObjectName("menuCategories")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_from_column = QtWidgets.QAction(MainWindow)
        self.actionLoad_from_column.setObjectName("actionLoad_from_column")
        self.actionRemove_options = QtWidgets.QAction(MainWindow)
        self.actionRemove_options.setObjectName("actionRemove_options")
        self.actionAdd_options = QtWidgets.QAction(MainWindow)
        self.actionAdd_options.setObjectName("actionAdd_options")
        self.actionConfirm_and_write = QtWidgets.QAction(MainWindow)
        self.actionConfirm_and_write.setObjectName("actionConfirm_and_write")
        self.actionHide_good_ones = QtWidgets.QAction(MainWindow)
        self.actionHide_good_ones.setObjectName("actionHide_good_ones")
        self.menuOpenFile.addAction(self.actionOpen)
        self.menuOpenFile.addAction(self.actionSave)
        self.menuCategories.addAction(self.actionLoad_from_column)
        self.menuCategories.addAction(self.actionRemove_options)
        self.menuCategories.addAction(self.actionAdd_options)
        self.menuCategories.addSeparator()
        self.menuCategories.addAction(self.actionConfirm_and_write)
        self.menuCategories.addSeparator()
        self.menuCategories.addAction(self.actionHide_good_ones)
        self.menubar.addAction(self.menuOpenFile.menuAction())
        self.menubar.addAction(self.menuCategories.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddButton.setText(_translate("MainWindow", "Add options"))
        self.ConfirmButton.setText(_translate("MainWindow", "Confirm and write"))
        self.FilterBox.setText(_translate("MainWindow", "Hide good ones"))
        self.LoadOptions.setText(_translate("MainWindow", "Load from column"))
        self.RemoveOption.setText(_translate("MainWindow", "Remove options"))
        self.menuOpenFile.setTitle(_translate("MainWindow", "Menu"))
        self.menuCategories.setTitle(_translate("MainWindow", "Categories"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Alt+O"))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionSave.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionLoad_from_column.setText(_translate("MainWindow", "Load from column"))
        self.actionLoad_from_column.setShortcut(_translate("MainWindow", "Alt+L"))
        self.actionRemove_options.setText(_translate("MainWindow", "Remove options"))
        self.actionRemove_options.setShortcut(_translate("MainWindow", "Alt+R"))
        self.actionAdd_options.setText(_translate("MainWindow", "Add options"))
        self.actionAdd_options.setShortcut(_translate("MainWindow", "Alt+A"))
        self.actionConfirm_and_write.setText(_translate("MainWindow", "Confirm and write"))
        self.actionConfirm_and_write.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionHide_good_ones.setText(_translate("MainWindow", "Hide good ones"))
        self.actionHide_good_ones.setShortcut(_translate("MainWindow", "Alt+H"))
